name: Build Kernel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            nasm \
            gcc \
            gcc-multilib \
            binutils \
            grub-pc-bin \
            grub-common \
            xorriso \
            mtools
 
      - name: rodar make clean
        run: make clean

      - name: Rodar make all
        run: make all

